# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
trigger:
- master

pool:
  name: default

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- task: NodeToolTest@0
  inputs:
    versionSpec: '12.x'
    checkLatest: true
  displayName: 'Install Node.js test'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Write-Host "Hello World"
      ls
- task: DeleteFilesNew@1
  inputs:
    SourceFolder: 
    Contents: '.*'
    DeleteFilesWithDot: true
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Write-Host "Hello World"
      ls

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
